import 'package:kimirina_app/models/agencias.dart';

final agenciesList = <Agencies>[
  Agencies(
    imageAsset: 'assets/images/agencia.png',
    city: 'Quito',
    services: [
      '- Asesoría en Prevención de VIH e ITS',
      '- Pruebas Rápidas VIH',
      '- Pruebas para ITS',
      '- Asesoria, vinculación a tratamiento VIH',
      '- Tratamiento ITS',
      '- PREP',
      '- Condones',
      '- Lubricantes',
    ],
    lat: -0.205294,
    lng: -78.488857,

  ),
  Agencies(
    imageAsset: 'assets/images/agencia.png',
    city: 'Guayaquil',
    services: [
      '- Asesoría en Prevención de VIH e ITS',
      '- Pruebas Rápidas VIH',
      '- Pruebas para ITS',
      '- Asesoria, vinculación a tratamiento VIH',
      '- Tratamiento ITS',
      '- PREP',
      '- Condones',
      '- Lubricantes',
    ],
lat: -2.191523,
    lng: -79.883687,

  ),
  Agencies(
      imageAsset: 'assets/images/agencia.png',
      city: 'Machala',
      services: [
        '- Asesoría en Prevención de VIH e ITS',
        '- Pruebas Rápidas VIH',
        '- Pruebas para ITS',
        '- Asesoria, vinculación a tratamiento VIH',
        '- Tratamiento ITS',
        '- PREP',
        '- Condones',
        '- Lubricantes',
      ],
      lat: -3.260251,
      lng: -79.957012,
  ),
  Agencies(
      imageAsset: 'assets/images/agencia.png',
      city: 'Esmeraldas',
      services: [
        '- Asesoría en Prevención de VIH e ITS',
        '- Pruebas Rápidas VIH',
        '- Pruebas para ITS',
        '- Asesoria, vinculación a tratamiento VIH',
        '- Tratamiento ITS',
        '- PREP',
        '- Condones',
        '- Lubricantes',
      ],
      lat: -2.191523,
      lng: -79.883687),
  Agencies(imageAsset: 'assets/images/agencia.png',
      city: 'Portoviejo',
      services: [
        '- Asesoría en Prevención de VIH e ITS',
        '- Pruebas Rápidas VIH',
        '- Pruebas para ITS',
        '- Asesoria, vinculación a tratamiento VIH',
        '- Tratamiento ITS',
        '- PREP',
        '- Condones',
        '- Lubricantes',
      ],
      lat: -2.191523,
      lng: -79.883687),
  Agencies(imageAsset: 'assets/images/agencia.png',
      city: 'Santo Domingo',
      services: [
        '- Asesoría en Prevención de VIH e ITS',
        '- Pruebas Rápidas VIH',
        '- Pruebas para ITS',
        '- Asesoria, vinculación a tratamiento VIH',
        '- Tratamiento ITS',
        '- PREP',
        '- Condones',
        '- Lubricantes',
      ],
      lat: -2.191523,
      lng: -79.883687),
  Agencies(imageAsset: 'assets/images/agencia.png',
      city: 'Santa Elena',
      services: [
        '- Asesoría en Prevención de VIH e ITS',
        '- Pruebas Rápidas VIH',
        '- Pruebas para ITS',
        '- Asesoria, vinculación a tratamiento VIH',
        '- Tratamiento ITS',
        '- PREP',
        '- Condones',
        '- Lubricantes',
      ],
      lat: -2.191523,
      lng: -79.883687)
];